TOKEN=$(curl -s 'https://www.boursobank.com/credit/credit-immobilier' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'accept-language: fr-FR,fr;q=0.9' \
  -H 'priority: u=0, i' \
  -H 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-site: none' \
  -H 'sec-fetch-user: ?1' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' | grep 'window.BRS_CONFIG' | awk '{print $3}' | jq -r .DEFAULT_API_BEARER 2>/dev/null)
TOKEN2=$(curl -s 'https://api.boursorama.com/appregistry/services/api/v1.7/_public_/bearer/app/jwt/web_fr_showcase_21_js' \
  -H 'Accept: */*' \
  -H 'Accept-Language: fr-FR,fr;q=0.9' \
  -H "Authorization: Bearer $TOKEN" \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Origin: https://www.boursobank.com' \
  -H 'Referer: https://www.boursobank.com/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  --data-raw '{"scopes":["ROLE_JS_PUBLIC_SHOWCASE_21"],"payload":{}}' | jq -r .initialBearer)

curl -s 'https://api.boursobank.com/services/api/v1.7/_public_/bank/mortgagesimulator/simulate' \
  -H 'accept: application/json' \
  -H 'accept-language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H "authorization: Bearer $TOKEN2" \
  -H 'content-type: application/json; charset=UTF-8' \
  -H 'origin: https://www.boursobank.com' \
  -H 'priority: u=1, i' \
  -H 'referer: https://www.boursobank.com/' \
  -H 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' \
  -H 'x-referer-feature-id: _._.vue_brs_mortgage_simulator' \
  --data-raw '{"migration":true,"ageHolder":38,"incomeHolder":46800,"ageCoHolder":0,"incomeCoHolder":0,"incomeOther":0,"charge":0,"performanceTag":"B","insuranceRateHolder":100,"insuranceRateCoHolder":0,"insuranceLevelHolder":2,"insuranceLevelCoHolder":0,"amount":250000,"works":0,"duration":19,"contribution":70000}' | jq .rate