version: '3.5'
services:
  app:
    restart: unless-stopped
    build:
      context: .
    environment:
      TZ: Europe/Paris
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- /:/hostfs:ro
      - /proc:/hostproc:ro
    network_mode: host
    env_file: .env

  # influxdb:
  #   restart: unless-stopped
  #   image: influxdb:1.8
  #   network_mode: host
